#+build darwin
package vulkan_backend

import vk "vendor:vulkan"

INSTANCE_FLAG :: vk.InstanceCreateFlags{.ENUMERATE_PORTABILITY_KHR}

INSTANCE_EXTENSIONS :: []cstring {
	vk.KHR_SURFACE_EXTENSION_NAME,
	vk.EXT_METAL_SURFACE_EXTENSION_NAME,
	vk.KHR_PORTABILITY_ENUMERATION_EXTENSION_NAME,
}

DEVICE_EXTENSIONS :: []cstring{vk.KHR_SWAPCHAIN_EXTENSION_NAME, vk.KHR_PORTABILITY_SUBSET_EXTENSION_NAME}
